spring:
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/library_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true