spring:
  sql:
    init:
      mode: never
  datasource:
    hikari:
      allow-pool-suspension: true
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/library_database
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: postgres